apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-backend
spec:
  selector:
    matchLabels:
      app: accounting-backend
  template:
    metadata:
      labels:
        app: accounting-backend
    spec:
      containers:
        - name: accounting-backend
          image: gubarsergey/accounting-backend
          ports:
            - containerPort: 80
          imagePullPolicy: Always
